config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  patch 'posts/:id' => 'posts#update'
  get 'posts/:id/edit' => 'posts#edit', as:'edit_post'
  get 'posts/america' => 'posts#america'
  get 'posts/canada' => 'posts#canada'
  get 'posts/uk' => 'posts#uk'
  get 'posts/aus' => 'posts#aus'
  get 'posts/sf' => 'posts#sf'
  get 'posts/ny' => 'posts#ny'
  resources :users, only: [:show]
  resources :posts do 
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    has_many :comments, dependent: :destroy
    mount_uploader :video, VideoUploader
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :comments, dependent: :destroy
         has_many :posts, dependent: :destroy
         validates :name, presence: true 
         validates :profile, length: { maximum: 200 } 
        mount_uploader :image, ImageUploader
        end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      post = Post.find(params[:post_id])
      comment = post.comments.build(comment_params) 
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) 
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) 
      end
    end
    private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
      if params[:search] == nil
          @posts= Post.all
        elsif params[:search] == ''
          @posts= Post.all
        else
          #部分検索
          @posts = Post.where("america LIKE ? ",'%' + params[:search] + '%')
        end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end
    
  def create
    post = Post.new(post_params)
    post.user_id = current_user.id
    if post.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to action: :index
  end
  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to :action => "show", :id => post.id
    else
      redirect_to :action => "new"
    end
  end
  def america
    @posts = Post.all
  end
  
  def canada
    @posts = Post.all
  end
  
  def uk
    @posts = Post.all
  end

  def aus
    @posts = Post.all
  end

  def sf
    @posts = Post.all
  end

  def ny
    @posts = Post.all
  end
  
  private
  def post_params
    params.require(:post).permit(:content, :country, :city, :school, :image,:lat,:lng)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]
    def index
        @tweets = Tweet.all
    end

    def new
        @tweet = Tweet.new
      end
    
      def create
        tweet = Tweet.new(tweet_params)
        if tweet.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
      def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
      end
      private
  def tweet_params
    params.require(:post).permit(:content, :country, :city, :school, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studyabroad</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <div class="header-logo">
    
  </div>
  <div class="openbtn"><span></span><span></span><span></span></div>
  <nav id="g-nav">
    <div id="g-nav-list">  
      <ul>
        <li><%= link_to "トップ", posts_path %></li>  
        <li><%= link_to "アメリカ", posts_america_path %></li>  
        <li><%= link_to "カナダ", posts_canada_path %></li>  
        <li><%= link_to "イギリス", posts_uk_path %></li>
        <li><%= link_to "オーストラリア", posts_aus_path %></li>  
        <% if user_signed_in? %>
          <li><%= link_to "マイページ", user_path(current_user.id) %></li>
        <% else %>
          <li><%= link_to "Signin", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>  
      </ul>  
    </div>
  </nav>
</header>
 <main>
    <%= yield %>
    </main>
  </body>
</html>

<script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
 <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

 <script>
$(".openbtn").click(function () {
 $(this).toggleClass("active");
 $("#g-nav").toggleClass("panelactive");
});
$("#g-nav a").click(function () {
 $(".openbtn").removeClass("active");
 $("#g-nav").removeClass("panelactive");
});
</script>

app/views/posts/america.html.erb
<h1>アメリカ<h1>
<% @posts.each do |t| %>
    <% if t.category == "america" %>  
    <p>内容:<%= t.content %></p>
    <% end %>

<% end %>

app/views/posts/canada.html.erb
<h1>カナダ<h1>
<% @posts.each do |t| %>
    <% if t.category == "canada" %>  
    <p>内容:<%= t.content %></p>
    <% end %>
  <% end %>

app/views/posts/index.html.erb
<h1>Stubroadgram</h1>


<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="Encode" onclick="codeAddress()">

<!-- 動画背景 -->
<div class="wrap">
 <!-- 背景用の動画ファイル -->
 <video id="bg-video" src="video/airplane.mp4" poster="poster.jpg" autoplay loop></video>
 <!-- 背景の上に表示させたいコンテンツ -->
 <div class="header-title">
 <p>
 To infinity and beyond!!
 </p>
 </div>
</div>

<div class="posts-link">
 <%= link_to "新規投稿ページへ", new_post_path %>
</div>
<h3>一覧ページ</h3>
<h2>gmap</h2>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
  <% end %>

<div class="posts-container">
  <% @posts.each do |t| %>
    <div class="post">
    <%= link_to t.user.name, user_path(t.user.id) %>
    <%= t.user.email %> 
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.content %>
      <%= t.country %>
      <%= t.city %>
      <%= t.school %>
  <% end %>
</div>



<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
    function initMap() {

      //初期表示位置
      let latlng = new google.maps.LatLng(38.60, 139.5);
      //デザイン
      let styles = [
           {
            stylers: [
             { "saturation": 0 },
             { "lightness": 0 }
            ]
           }
          ];

      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5.5,
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

//複数マーカー ここから
      <% @posts.each do |post|%>
        ( function() { 
          let markerLatLng = { lat: <%= post.lat %>, lng: <%= post.lng %> }; // 緯度経度のデータ作成
          let marker = new google.maps.Marker({ 
            position: markerLatLng, 
            map: map 
          });
//マーカーをクリックしたとき、詳細情報を表示
          let infowindow = new google.maps.InfoWindow({
            position: markerLatLng,
            content: "<a href='<%= post_url(post.id) %>' target='_blank'><%= post.city %></a>"
          }); //ここで詳細ページへのリンクを表示させる
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });

       })();
      <% end %>
      //複数マーカー ここまで  
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDayWOD0E9pX6QwAhq8ewxVcLd-m0cJRMg&callback=initMap" async defer></script>

<% if user_signed_in? %>
<a href="" class="btn btn--circle"><i class="far fa-envelope"></i><br> 
<%= button_to "ログアウト", destroy_user_session_path, method: :delete %>
<i class="fas fa-angle-down fa-position-bottom"></i></a>
<% end %>

app/views/posts/new.html.erb
<h1>Stubroadgram</h1>
<h3>新規投稿ページ</h3>
<%= form_for @post do |f| %>

    <div class="field">
    <%= f.label :content  %>
    <%= f.text_area :content, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :school %>
    <%= f.text_field :school, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :video %>
    <%= f.file_field :video, :accept => 'video/*' %>
</div>
<%= f.label :category %>
<%= f.select :category, [["アメリカ", "america"], ["カナダ", "canada"], ["イギリス", "uk"],["オーストラリア", "aus"]], include_blank: "どの投稿？" %>
<%= f.label :lat,"緯度" %>
    <%= f.text_field :lat,:value =>"緯度", id: :lat %>
    <%= f.label :lng,"経度" %>
    <%= f.text_field :lng,:value =>"経度", id: :lng %>
  <%= f.submit "Tweetする" %>
<% end %>

<div class="mappppp">
    <div class="kennsakumap">
      <div class="field">
        <input 
        class="text" 
        type="textbox"
        placeholder="マップ検索"
        onkeyup="this.setAttribute('value', this.value);"
        id="address"
        value=""/>
        <label class="label">マップ検索</label>
        <label class="error"></label>
        
      </div>
    </div>



<h2>Map</h2>

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="検索" onclick="codeAddress()">
<p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,
    
  });
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }

        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true	// ドラッグ可能にする
        });

        //二度目以降か判断
        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDayWOD0E9pX6QwAhq8ewxVcLd-m0cJRMg&callback=initMap" async defer></script>

app/views/posts/school.html.erb
<h1>学校<h1>
<% @posts.each do |t| %>
    <% if t.category == "school" %>  
    <p>内容:<%= t.content %></p>
    <% end %>
  <% end %>

app/views/posts/show.html.erb
<div class="comment-wrapper">
<p>コメント一覧</p>
<% @comments.each do |c| %>
  <div>
    <%= c.user.email unless c.user.blank? %>
    <br>
    <%= c.content %>
  </div>
    <br>
<% end %>
<% if user_signed_in? %>
<%= form_with(model: [@post, @comment], local: true) do |f| %>
  <%= f.text_area :content %>
  <%= button_tag type: "submit" do %>
    <i class="far fa-comments"></i> コメントする
  <% end %>
<% end %>
<p>
  <%= link_to @post.video_url.to_s do %>
   <%= video_tag(@post.video.to_s) %>
  <% end %>
</p>
<%= link_to "編集する", edit_post_path(@post.id) %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>
<%= image_tag @user.image_url, size: "250x200" if @user.image? %>
<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.posts.each do |t| %>
  <%= t.user.name %>
  <%= t.content %>
<% end %>

<%= link_to "Tweet一覧に戻る", posts_path %>